# Generated by Django 5.2.5 on 2025-08-31 10:50

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name for the AirTag', max_length=255)),
                ('master_key', models.CharField(max_length=116, validators=[django.core.validators.MinLengthValidator(116)])),
                ('skn', models.CharField(max_length=44, validators=[django.core.validators.MinLengthValidator(44)])),
                ('sks', models.CharField(max_length=44, validators=[django.core.validators.MinLengthValidator(44)])),
                ('paired_at', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.tag')),
            ],
            options={
                'unique_together': {('tag', 'latitude', 'longitude', 'timestamp')},
            },
        ),
    ]
