# Generated by Django 5.2.5 on 2025-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='paired_at',
            field=models.DateTimeField(),
        ),
    ]
