# Generated by Django 6.0.5 on 2026-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_tag_paired_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taglocation',
            index=models.Index(fields=['tag', '-timestamp'], name='taglocation_tag_timestamp_idx'),
        ),
    ]
