# Generated by Django 6.0.6 on 2026-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_taglocation_taglocation_tag_timestamp_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglocation',
            name='battery',
            field=models.CharField(blank=True, choices=[('full', 'Full'), ('medium', 'Medium'), ('low', 'Low'), ('very_low', 'Very low')], default=None, max_length=8, null=True),
        ),
    ]
