services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - src/api/.env.tests
    ports:
      - "5432:5432" # not needed but convenient for running django in true local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: ./src/api/.
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - src/api/.env.tests
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
  migration:
    build: ./src/api/.
    depends_on:
      - django
    env_file:
      - src/api/.env.tests
    command: python manage.py migrate

volumes:
  postgres_data:
