services:
  db:
    image: postgres:14.4-alpine
    env_file:
      - src/api/.env.tests
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # not needed but convenient for running django in true local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: