services:
  nginx:
    image: nginx:alpine
    depends_on:
      - backoffice
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
    ports:
      - "80:80"
  db:
    image: postgres:17.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backoffice:
    build: ./src/backoffice/.
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      TIME_ZONE: ${TIME_ZONE}
      NOTIFY_COOLDOWN_MINUTES: ${NOTIFY_COOLDOWN_MINUTES}
    ports:
      - "127.0.0.1:8000:8000"
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
  notifier:
    build: ./src/backoffice/.
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      NOTIFY_COOLDOWN_MINUTES: ${NOTIFY_COOLDOWN_MINUTES}
    command: python manage.py notifier
  migrations:
    build: ./src/backoffice/.
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      NOTIFY_COOLDOWN_MINUTES: ${NOTIFY_COOLDOWN_MINUTES}
    command: python manage.py migrate
  collectstatic:
    build: ./src/backoffice/.
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
      - static:/app/static
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      NOTIFY_COOLDOWN_MINUTES: ${NOTIFY_COOLDOWN_MINUTES}
    command: python manage.py collectstatic --noinput
  fetcher:
    build: ./src/fetcher/.
    environment:
      API_URL: ${API_URL}
      SLEEP_SECONDS: ${SLEEP_SECONDS}
      TAGS_REFRESH_SECONDS: ${TAGS_REFRESH_SECONDS}
    restart: unless-stopped

volumes:
  postgres_data:
  static:
