services:
  nginx:
    image: nginx:alpine
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: postgres:17.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - src/api/.env.tests
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: ./src/api/.
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - src/api/.env.tests
    command: python manage.py runserver 0.0.0.0:8000
  migrations:
    build: ./src/api/.
    depends_on:
      - django
    env_file:
      - src/api/.env.tests
    command: python manage.py migrate
  fetcher:
    build: ./src/fetcher/.
    env_file:
      - src/fetcher/.env.tests
    restart: unless-stopped

volumes:
  postgres_data:
