# Generated by Django 5.2.5 on 2025-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lock',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveConstraint(
            model_name='lock',
            name='unique_tag_per_lock',
        ),
        migrations.AddField(
            model_name='historicallock',
            name='schedule_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='historicallock',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallock',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lock',
            name='schedule_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='lock',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lock',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallock',
            name='radius',
            field=models.IntegerField(help_text='in meters'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='radius',
            field=models.IntegerField(help_text='in meters'),
        ),
    ]
