# Generated by Django 5.2.5 on 2025-09-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_alter_lock_options_remove_lock_unique_tag_per_lock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallock',
            name='last_notified',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='last_notified',
        ),
    ]
