# Generated by Django 5.2.5 on 2025-09-24 13:05

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_remove_historicallock_last_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallock',
            name='schedule_day',
        ),
        migrations.RemoveField(
            model_name='historicallock',
            name='schedule_end_time',
        ),
        migrations.RemoveField(
            model_name='historicallock',
            name='schedule_start_time',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='schedule_day',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='schedule_end_time',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='schedule_start_time',
        ),
        migrations.CreateModel(
            name='LockSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='locks.lock')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
