# Generated by Django 5.2.5 on 2025-09-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0004_remove_historicallock_schedule_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='lockschedule',
            name='created',
        ),
        migrations.RemoveField(
            model_name='lockschedule',
            name='modified',
        ),
    ]
