# Generated by Django 5.2.5 on 2025-08-23 08:44

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(help_text='Unique identifier for the AirTag', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name for the AirTag', max_length=255)),
                ('master_key', models.CharField(max_length=28, validators=[django.core.validators.MinLengthValidator(28)])),
                ('skn', models.CharField(max_length=44, validators=[django.core.validators.MinLengthValidator(44)])),
                ('paired_at', models.DateField(help_text='Date when the AirTag was paired')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the location', max_digits=9)),
                ('tag', models.ForeignKey(help_text='Associated AirTag', on_delete=django.db.models.deletion.CASCADE, to='locations.tag')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
