name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  code-format:
    name: Run code formatting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install uv
          cd src/frontend && npm ci
      - name: Run format checks
        run: make local/format-check

  docker-compose-format:
    name: Run docker compose linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: zavoloklom/dclint:alpine
          options: -v ${{ github.workspace }}:/mnt
          run: /bin/dclint /mnt -c /mnt/.dclintrc --max-warnings 0 -r

  dockerfile-format:
    name: Run dockerfile linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/backoffice/Dockerfile

  migrations:
    name: Forgotten migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          make docker/migrations-check

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          make docker/tests