name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Run code formatting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - name: Forgotten migrations
        run: |
          make docker/migrations-check
      - name: Unit tests
        run: |
          make docker/tests